### ISSUE TITLE
Inconsistent use of monospace in displays

### ISSUE THREAD

**Issue by XeR** [TFNS/CTFNote#113]
Table display uses `<pre>` which displays line breaks faithfully.
Every other display do not.

We should be consistent : either drop `<pre>` from table display, or use `<pre>` everywhere.
Using `<pre>` looks better, but we might encounter issues when tasks have multiple lines (see comments in #93)

**Comment by JJ-8** [comment]
As already said in #111, dropping `<pre>` solves the issue of newlines and word wrapping. Therefore I think it is better to drop `<pre>` instead of adding `<pre>` everywhere. It is also not worth the trouble in my opinion.

**Comment by JJ-8** [comment]
Closing since of #148
