### ISSUE TITLE
Calendar and PAST  not working with reverse proxy (nginx)

### ISSUE THREAD

**Issue by presianbg** [TFNS/CTFNote#119]
Hi,

Thanks for the awesome project!
The `Calnendar` section is not showing the CTFs I've imported:

![image](https://user-images.githubusercontent.com/2163486/144456183-fa32160d-4f30-40a4-9440-bfc62c40ce51.png)
![image](https://user-images.githubusercontent.com/2163486/144456207-04d7a2f7-f912-4c90-88e6-5d53dd591086.png)

There is no errors on in the web browser console and can't find anything wrong in the nginx logs.
How to diagnose the problem ? 

I can see that you are about the merge a new functionality to the Calendar - #116 , so my other question is - how to update my instance once you merge the changes ? 

**EDIT**:
Just tested on a local instance without nginx and it works:
![image](https://user-images.githubusercontent.com/2163486/144458675-75c56fff-0521-4c00-8761-8728fcdf753b.png)

So the issue could (should) be in the reverse proxy. 

Cheers,
PY

**Comment by presianbg** [comment]
For some reason when deploying with those settings:
![image](https://user-images.githubusercontent.com/2163486/144462587-14fb7cb4-ce68-4d04-af5b-fb3269827966.png)
`Calendar` and `PAST` are not working. 

Do I need to define port `1337`  or just the domain is OK in:
`+CMD_DOMAIN=example.org:1337`
?

**Comment by presianbg** [comment]
I think I have found the issue - there was 3 CTFs with `start` and `end` date at the same time and with same names, those were my tests when I was figuring the apps logic. 
I was not able to delete those entries from the graphql / database , so I started again and now everything works fine. 

Sadly, I was not able to reproduce the issue on my local setup :(

**Comment by presianbg** [comment]
So the only question left is - what is the right way (without loosing data) to refresh the docker containers, once you publish an update ?

**Comment by JJ-8** [comment]
> So the only question left is - what is the right way (without loosing data) to refresh the docker containers, once you publish an update ?

This question is unrelated to the issue, right? If so, the answer:

The data is stored persistent in a docker volume. So if you shutdown the docker containers, the data is not lost. So for updating, just shutdown the container, update the repository and force rebuild the docker container. If you start the containers, CTFNote will automatically update the database if required and everything is updated!

**Comment by XeR** [comment]
For the record, here is how I usually upgrade :

```
# Make a backup of the database, in case something goes wrong
sudo docker-compose exec -u postgres db pg_dumpall -U ctfnote > 2021-12-05-backup.sql

# Retrieve new commits
git stash
git pull --rebase
git stash pop

# Rebuild the containers
sudo docker-compose build

# Replace the containers with the updated ones
sudo docker-compose up -d
```
