### ISSUE TITLE
Add tags to tasks and filter or search by tag

### ISSUE THREAD

**Issue by itasahobby** [TFNS/CTFNote#140]
Would be nice to be able to add one or more tags to a task. Let's say you have a task inside Web category but you would want to tag it as "XSS" so when you are on a CTF you can search for past tasks you've done with that particular tag.

**Comment by XeR** [comment]
Hello !

We've been thinking about adding tags to tasks for a while now.

cf. BitK's answer to #27:
> I think we should fix this bug and #90 a the same time, and switch from task category to task "tags".

Additionally, there is #129 that seems related to your request (being able to search for all the XSS tasks you did before)

**Comment by JJ-8** [comment]
I have created an implementation of #90 and included the possibility to search through the tasks by tags using the global search functionality. @itasahobby, if you have time to help testing the branch https://github.com/JJ-8/CTFNote/tree/0-tags, that would be greatly appreciated!

**Comment by itasahobby** [comment]
@JJ-8 Just reviewed the new features and they work as expected, good job 👍🏻
