### ISSUE TITLE
Cannot create new task

### ISSUE THREAD

**Issue by deltaclock** [TFNS/CTFNote#152]
Hello,

Im trying to run this project by cloning the latest version and starting the containers with docker-compose.

While I can create a new ctf, I cant create any manual new tasks under it using the create button.

Am I doing something wrong or this a bug?

Thanks

**Comment by SakiiR** [comment]
Hi !

I faced the same issue recently with the `main` branch, I think it's due to the actual hedgedoc configuration.

As a quick fix, you can use the `dev` branch which works fine.

**Comment by JJ-8** [comment]
Closing this issue since the dev branch is merged into main. If this issue still persist, feel free to reopen this issue.

**Comment by anthares101** [comment]
Hello, Im having this same problem problem. For me the solution is to change the PAD_CREATE_URL variable in the api service to:
https://<my_domain>/pad/new. In previous versions everything was working fine, I don't know if maybe I'm missing something.
