### ISSUE TITLE
API consumes a lot of memory when importing from CTFd

### ISSUE THREAD

**Issue by jhthenerd** [TFNS/CTFNote#17]
When importing a relatively large CTFd JSON file (~55kb), the API consumes a lot of CPU and RAM (it managed to exhaust 4GB of RAM and hang up the API thread)
The tasks do get imported, but it was only able to get through ~15 tasks before running out of memory.

The JSON I used (obtained from the picoCTF 2019 API):
https://pastebin.com/YCUMh1qM

Logs from the API container:
https://pastebin.com/VipdguRH

**Comment by B-i-t-K** [comment]
That's a bit weird, the JSON is parsed client side
Are you sure the memory was not taken by another process ?

**Comment by SakiiR** [comment]
@B-i-t-K The front is sending multiple request for each task right ? Maybe the task creation ( On the API side ) routine is consuming too much in this specific situiation.

**Comment by SakiiR** [comment]
when* importing many tasks.

This last commit fixed the issue on my local setup.

Please @jhthenerd, can you retry with the fix in place ( https://github.com/TFNS/CTFNote/commit/5cc916c0dcf9b470a487ffeb52b6c238728df226 ) ? thanks

**Comment by SakiiR** [comment]
Thanks to you for the report, cheers
