### ISSUE TITLE
CTFNote 2.1.2

### ISSUE THREAD

**Issue by XeR** [TFNS/CTFNote#198]
> I would also suggest to bump the version of CTFNote after merging this PR.

_Originally posted by @JJ-8 in https://github.com/TFNS/CTFNote/issues/197#issuecomment-1345290621_

- [x] #197: Add context menu to task dropdown
- [x] #193: Add HTB parser
- [x] Upgrade dependencies to fix some vulnerabilities

**Comment by JJ-8** [comment]
I have merged #199 and created a new release, together with a new tag.
