### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by vishiswoz** [TFNS/CTFNote#21]
Is it possible to host the docker container through Github pages?

**Comment by vishiswoz** [comment]
For example, instead of accessing the frontend through http://127.0.0.1/ I can instead access it through http(s)://<username>.github.io

**Comment by SakiiR** [comment]
Github pages allows you to host static contents only. It allows you to setup a DNS name redirection as well but that will not help you.

You might want to host ctfnote on a server you own, with a remote access ( SSH ) to setup docker and start the project.

Maybe you want to take a look at https://github.com/yeswehack/pwn-machine if you want to setup your own infrastructure :) CTFNote works well with it.

**Comment by vishiswoz** [comment]
Thanks for the response, that's what i assumed but i wanted to make sure. I'll check out that repository as well, thanks!
