### ISSUE TITLE
Frontend not synced with backend Discord status

### ISSUE THREAD

**Issue by daanbreur** [TFNS/CTFNote#292]
Currently the backend doesn't know if the Discord integration is enabled or disabled.

Proposed fix:
- add "discord_integration_enabled" to the "ctfnote.settings" table, readable by user_guest.
- write to this field every time the database (and bot) are started, write a false or true respectively.
- read this just like the style configuration is read client sided
  - Display warning its disabled.
  - Or, hide element outright.

**Comment by daanbreur** [comment]
I would like some input. Should we remove the fields for Discord when its disabled, or show some kind of warning

![image](https://github.com/user-attachments/assets/c3b0df99-0838-4248-90fd-779515c035df)
^ See example edited with inspect element.

**Comment by JJ-8** [comment]
Fixed in #296
