### ISSUE TITLE
Allow for account creation from the Discord bot.

### ISSUE THREAD

**Issue by daanbreur** [TFNS/CTFNote#300]
Situation:
You are in a Discord server and want to get access to the CTFNote, there is possibly a pin somewhere with the invitation code which you can use to get your own account. However, you aren't done yet. You then will have to manually link your account.

Proposed Solution:
What if there was a better and quicker way of making an account and syncing your account to your discord. For this I propose a command, for example `/createaccount` or `/register` (name to be determined). Which will create an one-time invitation link, which, after used will automatically link the Discord id to the just created user.

![image](https://github.com/user-attachments/assets/0b1fa11d-fc76-4f5b-b500-8c332772b934)

There is also an option that the Discord bot checks if the user has a specific role and only if they have this role allows to create their own account using this command.
This option can also be turned off using environment variables.

The one-time invitation links that can be created through the admin dashboard remain unchanged and will just create the account without any additional linking.

**Comment by JJ-8** [comment]
Fixed by https://github.com/TFNS/CTFNote/pull/301
