### ISSUE TITLE
Session cookie is not being deleted on logout

### ISSUE THREAD

**Issue by presianbg** [TFNS/CTFNote#33]
Hi,

Thanks for the awesome project! 
I have tried both the `main` and the `dev` branch and looks like the session cookie is not cleared after pressing the `Logout` button.
Maybe its something specific to my env. 
Can you confirm that it works for you ? 

Cheers,
PY

**Comment by B-i-t-K** [comment]
Thanks for the report, we are currently working (and almost finished) on a big update. 
This bug (and many other) will be fixed in the next release.

**Comment by presianbg** [comment]
Sounds awesome! Thank you!
