### ISSUE TITLE
Make CTF easier to access

### ISSUE THREAD

**Issue by XeR** [TFNS/CTFNote#37]
Accessing a CTF requires clicking on its name on the graphql branch.
This is not obvious for a new user. main branch has an `OPEN CTF` button.
commit: a6420a3c95b2347b06f59166b6ed1fb2e66e0f00

It would feel more natural to be able to click on the whole card.
A button like the current version (or any other indicator) is fine too

**Comment by SakiiR** [comment]
Does that look good to you @XeR ?

![Screenshot_1](https://user-images.githubusercontent.com/9950578/115615686-907e1e80-a2ef-11eb-81ad-73459dd5dd5c.png)

**Comment by XeR** [comment]
LGTM
