### ISSUE TITLE
Building api step 2/10

### ISSUE THREAD

**Issue by GimmeAUnicorn** [TFNS/CTFNote#5]
Installing this on my Rpi Zero. Getting the following error.
`pi@raspberrypi:~/CTFNote $ sudo docker-compose up -d
Building api
Step 1/10 : FROM node:14.5.0-alpine3.10
 ---> 26cac906db96

Step 2/10 : RUN mkdir -p /usr/src/app &&     apk add openssh-client g++ make python
 ---> Running in 76de4a468273

ERROR: Service 'api' failed to build : The command '/bin/sh -c mkdir -p /usr/src/app &&     apk add openssh-client g++ make python' returned a non-zero code: 139`

**Comment by XeR** [comment]
Hello !

This might be related to #3 and #4.

Can you try building commit `26fec6afded434b3718bf203797f52aa4a09e943` ? (`git checkout 26fec6afded434b3718bf203797f52aa4a09e943`)

Can you try cloning my fork and building it ? https://github.com/XeR/CTFNote

**Comment by GimmeAUnicorn** [comment]
Hey !

Tried both suggestions, still same error

**Comment by Dr1en** [comment]
Same error. Is there a fix @XeR ?

**Comment by XeR** [comment]
> Same error. Is there a fix @XeR ?

No. I do not have the required hardware to test.
Maybe @SakiiR knows what's up ?

Can you try to spawn a new container with :
```sh
docker container run --rm -it node:14.5.0-alpine3.10 /bin/sh
```

And report the output of the following commands :
```sh
which mkdir apk
mkdir -p /usr/src/app; echo $?
apk add openssh-client; echo $?
apk add g++; echo $?
apk add make; echo $?
apk add python; echo $?
```

**Comment by SakiiR** [comment]
I don't know what is up exactly unfortunaly.

Can't reproduce myself for the same reason =( 

Waiting for some technical details.

**Comment by XeR** [comment]
After getting my hands on hardware, I managed to pinpoint the root cause.
I could not run any Docker container because there isn't enough RAM.
If you *absolutely* need to run this on a raspi zero... you can download the ARMv6 stand-alone binaries from node, but you're on your own. Good luck !
