### ISSUE TITLE
Continued development

### ISSUE THREAD

**Issue by theS1LV3R** [TFNS/CTFNote#51]
Hi! I am the owner of the [CTFNote](https://github.com/CTFNote) organisation, a project almost identical to this one.

As my project has been abandoned (loss of motivation and energy for the project), it has been archived, and I am willing to give away the org.

Since this project is pretty big, splitting the individual components (frontend, backend, docs?) into individual repos could potentially be a good idea. As such, I'm proposing that this repo is moved over to my org, and ownership of the org is transferred over to you.

Alternatively, as the project's main branch hasn't been touched in four months, if continuing to maintain the project isn't wanted or desired by you, I could possibly take over the repo and maintain it. There is also the option of me forking the project and moving it over myself.

**Comment by SakiiR** [comment]
Hi @theS1LV3R ,

Thanks a lot for your offer! We discussed it a bit, and we do not see the need to make an org specifically for CTFNote at this point.

Feel free to delete the org if you want to get rid of it; if you end up keeping it and we change our mind on this topic at some point, we will definitely get in touch!

Although the project has not been updated for a while, we are still working on it; therefore, we plan to retain maintainership.

Thanks again!

SakiiR, on behalf of TFNS

**Comment by theS1LV3R** [comment]
Sounds good! 

I'll keep the org in case you decide to transfer it over and to prevent anyone else (who might not have the same good intentions) from taking the name.

I'll also have a look at the codebase for this repo, and see what issues can be worked on. I'd love to help out!

**Comment by SakiiR** [comment]
> I'll also have a look at the codebase for this repo, and see what issues can be worked on. I'd love to help out!

Check out the `graphql` branch in order to look at the codebase because pretty much everything has changed since then.

Happy hacking
