### ISSUE TITLE
[Feature] Discord bot integration

### ISSUE THREAD

**Issue by theS1LV3R** [TFNS/CTFNote#53]
My team and many other teams i know of are using discord servers to communicate. If this tool could automatically:

- Assign roles
- Create channels
- Archive messages

i think that'd be really useful.

I'm not quite sure how it'd be implemented, but it'd be a cool feature nonetheless

**Comment by JJ-8** [comment]
Discord bot is now supported in version 3.0.0: https://github.com/TFNS/CTFNote/pull/237
