### ISSUE TITLE
Broken UI - Mobile support

### ISSUE THREAD

**Issue by posix-lee** [TFNS/CTFNote#6]
In the mobile environment, the UI of the top bar looks broken.
This is because its content exceeds the width that can be expressed in one line.

There are five suggestions for resolving this.

1. Give up mobile support
2. Remove the CTFNote string.
3. Remove the CTFNote string and make it selectable from the menu.
4. Replace the CTFNote string with a small logo.
5. Reduce the font size.

![image](https://user-images.githubusercontent.com/61380567/99923973-99d48080-2d7b-11eb-8beb-c32eed2753fe.png)

**Comment by B-i-t-K** [comment]
mobile support should be way better on v2
