### ISSUE TITLE
[Question] Will my changes be merged?

### ISSUE THREAD

**Issue by JJ-8** [TFNS/CTFNote#68]
Hello!

Amazing work with the new main branch! Really cool to see the Vue 3 / Quasar 2 / TypeScript migration and great to see that there is activity again!

While you were working on the `graphql` branch, I continued development on my own fork to get new features merged faster without disturbing your work on the new version. Since it is merged to master, I am willing to fork again and put my own changes on top of it. But my question is: should I create PRs for the changes or not? I really like to contribute to the upstream repo, but only if my changes are actually be merged (otherwise it only takes time to create branches and PRs).

It is about the following changes:

1. [Add player chips back to the task cards on the task overview](https://github.com/JJ-8/CTFNote/commit/76232854b3fbaf550e8101935347292e2bf3386c). 
    - This is because I really like to see in one glance who is working on what without having to hover over every task to see it. It is like the old behaviour of CTFNote where the names were visible at every task.
2. [Reload incoming CTFs when changed](https://github.com/JJ-8/CTFNote/commit/1505ef7bb0ebe5df03b71f2a5a8833e0b50731f4)
    - This is still a bug in the new CTFNote, the view is not updated if there is a new CTF added. This is probably related to this issue.
3. [Websocket support for Hedgedoc](https://github.com/JJ-8/CTFNote/commit/a98784ec4bafd26a9ed4ef28fcb962dc6eb50d21)
    - Instead of using HTTP long polling, websocket is much better and supported by Hedgedoc. It is only a little config switch in the nginx config.
4. [Deployment instructions for nginx](https://github.com/JJ-8/CTFNote/commit/55eeb61c0e29e4a87b5b290452e46e6c64eb8dca)
    - A specific config is required to use nginx with CTFNote. This is written in the README now. However, I changed some things: I bind to only localhost:8080 and instruct the user to use a HTTPS setup via nginx. So I don't expose CTFNote over insecure HTTP anymore. And there are some headers changed to work with Hedgedoc and HTTPS via CTFNote (these are some later commits in the repo).
5. Add Hedgedoc authentication when authenticating with CTFNote (multiple commits so I can not link it).
    - This will auto create accounts and login the user in Hedgedoc so their username will be displayed in Hedgedoc. They will have a cursor with a username and a 'git blame' will be visible in the pad. The code consists of some hacky database manipulation to make it work, but it does work (requires connection to the Hedgedoc database).
6. ['Past CTF' role in CTFNote](https://github.com/JJ-8/CTFNote/commit/512425e03b71ce55efc50aab8eb74451f9719252)
    - We introduced a new role in CTFNote: the 'Past CTF' role which means that a user should be invited to access upcoming CTFs but they have auto access to past CTFs. This is a role between guest and member. We found it very useful to grant to irregular users or if we use CTFNote with multiple teams.
7. [A CyberChef popup in the toolbar](https://github.com/JJ-8/CTFNote/commit/761fe0517e6466646f32287170b9bb4c6a4c372c)
    - There is a new button which allows users to quickly start multiple CyberChef instances in CTFNote.
![image](https://user-images.githubusercontent.com/34778827/137854564-6b1e3154-a935-4567-929c-1c19b57bef53.png)

I am curious if you like these changes, if I should contribute them to upstream and if the changes will be merged in a reasonable amount of time.

**Comment by XeR** [comment]
> Add player chips back to the task cards on the task overview

It was removed before we added the "dense" and "ultradense" themes.
If you can add it only on the "classic" theme, we see no reasons not to merge it.


> I don't know a better way than I have right now

The "cleanest" way seems to be [implementing an OAuth2 provider](https://docs.hedgedoc.org/configuration/#oauth2-login).
This looks like a complex task, but it would have the advantage of being able to work on a different domain.
Nothing set in stone though ! We like the idea of having an account on Hedgedoc, this will be implemented in the future.


> A CyberChef popup in the toolbar

Ah, so your workflow is to open a new pop-up, try some recipes and keep track of what worked/did not work on a pad ?
I understand now.
We'll talk about it. The current focus is fixing bugs so I don't think we'll add it on the short term.


> adding DestructiveFarm to the deployment for CTFNote

It's the first time I hear about DestructiveFarm.
We think this is not in the scope of CTFNote. Sorry.

As for the other patches (3, 4), you should be able to branch from main and cherry-pick them to keep the metadata. :-)
