### ISSUE TITLE
Add a way to search CTF or Tasks

### ISSUE THREAD

**Issue by B-i-t-K** [TFNS/CTFNote#80]
It could be nice to have a way to search CTF and Tasks by title or description

**Comment by SakiiR** [comment]
Maybe we can have some kind of search bar like discord (**CTRL+K**) or visual studio code (**CTRL+P**) to quickly move to a task/ctf.

**Comment by JJ-8** [comment]
Description is not implemented (yet), but with version 2.1.0 it is possible to search by title for a CTF or task! Thank you @SakiiR! 

If you feel like you really need description search too, feel free to open a new issue or reopen this one.
